#!/bin/bash
echo "Removing leftover files from install in Downloads (unzip)..."
sudo rm -rf ~/Downloads/arrow
echo "Removing leftover files from install in Downloads (zip)..."
sudo rm -rf ~/Downloads/arrow-text-editor.zip
